name: UMC Gradle Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: keyscan
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
    - name: secrets
      env: # Or as an environment variable
        MAVENCI: ${{ secrets.MAVENCI }}
      run: echo "${MAVENCI}" >> publish_key
    - name: Gradle uploadArchives
      run: ./gradlew uploadArchives
    - name: cleanup
      run: rm publish_key
